name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker Image
      run: |
        docker build -t my-node-app .

    - name: Run Tests
      run: |
        echo "No tests available yet."

    - name: Push to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker tag my-node-app ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest
